### ISSUE TITLE
logon error ?

### ISSUE THREAD

**Issue by pakozdy** [HylandSoftware/Harbor.Tagd#14] opened 2018-11-03 21:56 UTC
Hello .
ive got this problem when running own private harbor  registry. used dotnet 2.1 on centos 7.5 username and password are correct  (docker login .... ), url is accessible. self signed cert is used for nginx.  insecure registry key is correct for  https://reg1.xxx.zzz . Harbor an Tagd are on same machine.
any hints where problem is ? 

same as bug "Improve logging around cert issues" ?

 _dotnet ./dist/Harbor.Tagd.dll --config-file config.yml  --endpoint https://reg1.xxx.zzz --user zzzzz --password xxxxxxxx -v V_
[22:46:04 INF] Loading rules using Harbor.Tagd.Rules.FilesystemRuleProvider
[22:46:04 WRN] The rule provider did not return any explicit tag rules
[22:46:04 VRB] Using default rule {'Project': '.*', 'Repo': '.*', 'Tag': '.*', 'Keep': 1, 'Ignore': [latest]}
[22:46:04 VRB] Ignoring the following projects: []
[22:46:04 VRB] Ignoring the following repos: []
[22:46:04 VRB] Ignoring the following tags: ["latest"]
[22:46:04 WRN] Running in report-only mode. To delete tags, run with --destructive
[22:46:04 INF] Connecting to https://reg1.xxxx.zz as zzzzzzzz
[22:46:04 INF] Running in report-only mode
[22:46:05 INF] Logging out
[22:46:05 FTL] An Error was encountered while processing tags
System.InvalidOperationException: Not logged in
   at Harbor.Tagd.API.HarborClient.Logout() in /root/harbor.tagd/Harbor.Tagd-master/src/Harbor.Tagd/API/HarborClient.cs:line 61
   at Harbor.Tagd.TagEngine.Process() in /root/harbor.tagd/Harbor.Tagd-master/src/Harbor.Tagd/TagEngine.cs:line 104
   at Harbor.Tagd.Program.DoClean(ApplicationSettings appSettings, IRuleProvider rules) in /root/harbor.tagd/Harbor.Tagd-master/src/Harbor.Tagd/Program.cs:line 120
   at Harbor.Tagd.Program.Main(String[] args) in /root/harbor.tagd/Harbor.Tagd-master/src/Harbor.Tagd/Program.cs:line 90

thanks

**Comment by nlowe** [comment] 2018-11-03 22:53
The easiest way to fix this is to customize the docker image so it includes your CA Cert. Even though docker knows your registry is insecure, `tagd` does not and we don't have an option to disable certificate validation at the moment..

Duplicate of #9

**Closed by nlowe** 2018-11-03 22:53 UTC
